{{- if not .Values.naiDatabase.external }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nai-db-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: nai-db
    {{- include "nai-core.labels" . | nindent 4 }}
{{- if .Values.imagePullSecret.name }}
imagePullSecrets:
  - name: {{ .Values.imagePullSecret.name }}
{{- end }}
{{- end }}