apiVersion: v1
kind: ConfigMap
metadata:
  name: nai-ui-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: nai-ui
    {{- include "nai-core.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "enableLabs": {{ .Values.naiLabs.enabled }}
    }
