apiVersion: v1
kind: Service
metadata:
  name: nai-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: nai-ui
    {{- include "nai-core.labels" . | nindent 4 }}
spec:
  selector:
    app: nai-ui
  ports:
    - protocol: TCP
      port: 1900
      targetPort: 1900
