apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nai-otel-role-binding
  labels:
    app.kubernetes.io/component: opentelemetry
    {{- include "nai-core.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nai-otel-role
subjects:
  - kind: ServiceAccount
    name: nai-otel-sa
    namespace: {{ .Release.Namespace }}