apiVersion: v1
kind: Service
metadata:
  name: iam-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: nai-iam-ui
    {{- include "nai-core.labels" . | nindent 4 }}
spec:
  selector:
    app: iam-ui
  ports:
  - name: http
    port: 5557
    protocol: TCP
    targetPort: 5557