apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: iam-proxy-backend-tls-policy
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
    - kind: Service
      name: iam-proxy
      group: ""
  validation:
    hostname: iam-proxy.{{ .Release.Namespace }}.svc.cluster.local
    # TODO review secret after IAM chart
    caCertificateRefs:
      - kind: Secret
        name: ca-key-pair
        group: ""
