{{- if .Values.imagePullSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: nai-operators-helm-hooks-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nai-operators.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}