apiVersion: v1
kind: ServiceAccount
metadata:
  name: nai-operators-helm-hooks-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: nai-helm-hooks
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-weight: "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- include "nai-operators.labels" . | nindent 4 }}
imagePullSecrets:
  - name: nai-operators-helm-hooks-secret