apiVersion: v1
kind: ServiceAccount
metadata:
  name: nai-helm-hooks-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: nai-hooks
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- include "nai-core.labels" . | nindent 4 }}
imagePullSecrets:
  - name: nai-helm-hooks-secret