apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values "oauth2-proxy" "config" "existingSecret" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nai-core.labels" . | nindent 4 }}
type: Opaque
data:
  cookie-secret: {{ randAlphaNum 32 | b64enc | quote }}
