{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ printf "%s-clickhouse-metrics" (include "altinity-clickhouse-operator.fullname" .) }}
  namespace: {{ template "altinity-clickhouse-operator.namespace" . }}
  labels:
    {{- include "altinity-clickhouse-operator.labels" . | nindent 4 }}
  {{- if .Values.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.serviceMonitor.additionalLabels | nindent 4 }}
  {{- end }}
  annotations:
    {{- include "altinity-clickhouse-operator.annotations" . | nindent 4}}
spec:
  endpoints:
  - interval: 60s
    port: operator-metrics
  - interval: 60s
    port: clickhouse-metrics
  namespaceSelector:
    matchNames:
    - {{ template "altinity-clickhouse-operator.namespace" . }}
  selector:
    matchLabels:
      {{- include "altinity-clickhouse-operator.selectorLabels" . | nindent 6 }}
{{- end }}