apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: iam-themis-tls-cert
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: nai-iam-themis
    {{- include "nai-core.labels" . | nindent 4 }}
spec:
  secretName: iam-themis-tls-cert
  issuerRef:
    name: ca-issuer
    kind: Issuer
  commonName: iam-themis
  dnsNames:
  - iam-themis
  - iam-themis.{{ .Release.Namespace }}.svc.cluster.local