apiVersion: v2
appVersion: 791036aaf751787ed2719050d5086b2ba8642f1a
description: The Helm chart for Envoy AI Gateway CRD
home: https://aigateway.envoyproxy.io/
icon: https://raw.githubusercontent.com/envoyproxy/ai-gateway/refs/heads/main/site/static/img/logo.svg
keywords:
- gateway-api
- envoyproxy
- envoy-gateway
- eg
- ai-gateway
- ai
maintainers:
- name: envoy-ai-gateway-maintainers
  url: https://github.com/envoyproxy/ai-gateway/blob/main/CODEOWNERS
name: ai-gateway-crds-helm
sources:
- https://github.com/envoyproxy/ai-gateway
type: application
version: 0.0.0-791036aaf751787ed2719050d5086b2ba8642f1a
