# Assuming that gateway pod and envoy controller pod are in the same namespace.
{{- if .Values.imagePullSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  namespace: {{ .Values.envoy.namespace }}
  labels:
    {{- include "nai-operators.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
