{{- if .Values.naiLabs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nai-labs-data
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: nai-labs
    {{- include "nai-core.labels" . | nindent 4 }}
spec:
  {{- if .Values.defaultStorageClassName }}
  storageClassName: {{ .Values.defaultStorageClassName }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    {{- toYaml .Values.naiLabs.storageSpec.resources | nindent 4 }}
{{- end }}
