apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: nai-iep-operator
    {{- include "nai-core.labels" . | nindent 4 }}
  name: nai-iep-operator-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nai-iep-operator-role
subjects:
- kind: ServiceAccount
  name: nai-iep-controller-sa
  namespace: {{ .Release.Namespace }}
